name: "Wrangler"
description: "Wrangler Action"
runs:
  using: "node16"
  main: "main.js"
inputs:
  apiToken:
    description: "Cloudflare API Token"
    required: true
  accountId:
    description: "Cloudflare Account ID"
    required: true
  workingDirectory:
    description: "Working Directory"
    required: false
  wranglerVersion:
    description: "Wrangler Version"
    required: false
